### ISSUE TITLE
Somebody?

### ISSUE THREAD

**Issue by JJSILDesigner** [athrowaway2021/comix#27]
No problem with comix.py, but with unkindle.py i have tis problem:

PS X:x\comix-main> python  unkindle.py list      
Authenticating . . .
Could not acquire the manifest!
PS X:x\comix-main> python  unkindle.py B08CSYTX83
Authenticating . . .
download size: 12MB
Downloading the book . . 83%
Extracting . . .
B08CSYTX83 : Ecos- Caminhos desencontrados
Traceback (most recent call last):
  File "X:x\comix-main\unkindle.py", line 154, in <module>
    kindle.download()
  File "X:x\comix-main\unkindle.py", line 137, in download
    book.extract_to_folder(content_folder, f"{self.release_name} - p")
  File "X:x\comix-main\yj_to_folder.py", line 259, in extract_to_folder
    self.process_content(self.get_fragment(ftype="$608", fid=page_templates[0]))
  File "X:x\comix-main\yj_to_folder.py", line 137, in process_content
    self.process_content_list(story, num)
  File "X:x\comix-main\yj_to_folder.py", line 123, in process_content_list
    self.process_content(_content, num)
  File "X:x\comix-main\yj_to_folder.py", line 139, in process_content
    self.process_content_list(content, num)
  File "X:x\comix-main\yj_to_folder.py", line 123, in process_content_list
    self.process_content(_content, num)
  File "X:x\comix-main\yj_to_folder.py", line 139, in process_content
    self.process_content_list(content, num)
  File "X:x\comix-main\yj_to_folder.py", line 123, in process_content_list
    self.process_content(_content, num)
  File "X:x\comix-main\yj_to_folder.py", line 139, in process_content
    self.process_content_list(content, num)
  File "X:x\comix-main\yj_to_folder.py", line 123, in process_content_list
    self.process_content(_content, num)
  File "X:x\comix-main\yj_to_folder.py", line 227, in process_content
    raw_media = self.book_data["$417"] [resource["$165"]]
KeyError: '$165'
PS X:x\comix-main>

**Comment by athrowaway2021** [comment]
The Kindle scripts are just experiments and aren't expected or supposed to be working
