### ISSUE TITLE
Bad password for file 'COMIXOLOGY_BOOK_ENCRYPTED_HD_0001.jpg'

### ISSUE THREAD

**Issue by rainrdx** [athrowaway2021/comix#31]
It seems that for some books, the encoding mechanism might be a little bit different. Because this takes specific comic books to debug, more than happy to work privately on those cases The trace is as follows:

Getting auth token . . .
48386 : Fables - v07
Downloading page 000 . . .Traceback (most recent call last):
  File "[Redacted]\comix.py", line 150, in <module>
    cmx.download()
  File "[Redacted]\comix.py", line 126, in download
    zf.extractall(content_folder, pwd=image_key)
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2106, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2159, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2013, in open
    return self._open_to_read(mode, zinfo, pwd)
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2024, in _open_to_read
    raise e
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2021, in _open_to_read
    return self.zipextfile_cls(zef_file, mode, zinfo, True, pwd)
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 1203, in __init__
    self.read_init()
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 1218, in read_init
    self._decrypter = self.get_decrypter()
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 1306, in get_decrypter
    decrypter = self._decrypter_cls(
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile_aes.py", line 61, in __init__
    raise RuntimeError("Bad password for file %r" % zinfo.filename)
RuntimeError: Bad password for file 'COMIXOLOGY_BOOK_ENCRYPTED_HD_0001.jpg'

**Comment by DigitalManga** [comment]
at Line 84 of comix.py, add this and try again. handle the indentation by yourself
`
        if self.publisher_id == "0" or self.publisher_id == "250" or self.publisher_id == "34" or self.publisher_id == "3" :
            self.publisher_id = "1"`

**Comment by rainrdx** [comment]
@DigitalManga It works perfectly. Thank you!

**Comment by rainrdx** [comment]
@DigitalManga Interesting not working for another publisher.....again thank you for possibly looking into this..

663 : The Walking Dead - v01
Downloading page 000 . . .Traceback (most recent call last):
  File "[Redacted]\Comics\comix.py", line 150, in <module>
    cmx.download()
  File "[Redacted]\Comics\comix.py", line 126, in download
    zf.extractall(content_folder, pwd=image_key)
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2106, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2159, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2013, in open
    return self._open_to_read(mode, zinfo, pwd)
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2024, in _open_to_read
    raise e
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 2021, in _open_to_read
    return self.zipextfile_cls(zef_file, mode, zinfo, True, pwd)
  File "[Redacted]\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 1203, in __init__
    self.read_init()
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 1218, in read_init
    self._decrypter = self.get_decrypter()
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile.py", line 1306, in get_decrypter
    decrypter = self._decrypter_cls(
  File "[Redacted]\AppData\Roaming\Python\Python310\site-packages\pyzipper\zipfile_aes.py", line 61, in __init__
    raise RuntimeError("Bad password for file %r" % zinfo.filename)
RuntimeError: Bad password for file 'COMIXOLOGY_BOOK_ENCRYPTED_HD_0001.jpg'

**Comment by DigitalManga** [comment]
Remove the self.publisher_id == "0" from the previous one.

for the new one its

`if self.publisher_id == "6" or self.publisher_id == "7" or self.publisher_id == "10" or self.publisher_id == "7" or self.publisher_id == "8" : self.publisher_id = "4"`

**Comment by rainrdx** [comment]
@DigitalManga Sorry for one more, this time it is
225418 : Frank Millers Sin City - v01
Same error. I applied the same two hacks you offered. Sigh, sorry and thanks for working on this.

**Comment by rainrdx** [comment]
the same goes for
2255 : Hellboy - v01
I suppose something wrong with Dark Horse. Sorry seems that each publisher requires its own attention....

**Comment by DigitalManga** [comment]
comment out this line when downloading from the Dark Horse Comics. issue is that publisher id for Dark Horse is 3 so the below line changes it to 1

`if self.publisher_id == "250" or self.publisher_id == "34" or self.publisher_id == "3":
            self.publisher_id = "1"`

**Comment by DigitalManga** [comment]
check the publisher for the titles, image ones need the above line, while the others dont

you can create copies of the original py to cater a specific publisher. that way, you wont have issues with the duplicated publisher id

**Comment by rainrdx** [comment]
@DigitalManga This works wonders. Again thanks again and again
