### ISSUE TITLE
Error when downloading: Bad password for file 'COMIXOLOGY_BOOK_ENCRYPTED_HD_0001.jpg

### ISSUE THREAD

**Issue by Ju1810** [athrowaway2021/comix#38]
Hi,
When I try to download a comic book I purchased, I receive this error

D:\comix-main>python comix.py 1005546
Getting auth token . . .
1005546 : Fence- Rise
Downloading page 000 . . .Traceback (most recent call last):
  File "D:\comix-main\comix.py", line 155, in <module>
    cmx.download()
  File "D:\comix-main\comix.py", line 131, in download
    zf.extractall(content_folder, pwd=image_key)
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2106, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2159, in _extract_member
    with self.open(member, pwd=pwd) as source, \
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2013, in open
    return self._open_to_read(mode, zinfo, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2024, in _open_to_read
    raise e
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2021, in _open_to_read
    return self.zipextfile_cls(zef_file, mode, zinfo, True, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 1203, in __init__
    self.read_init()
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 1218, in read_init
    self._decrypter = self.get_decrypter()
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 1306, in get_decrypter
    decrypter = self._decrypter_cls(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile_aes.py", line 61, in __init__
    raise RuntimeError("Bad password for file %r" % zinfo.filename)
RuntimeError: Bad password for file 'COMIXOLOGY_BOOK_ENCRYPTED_HD_0001.jpg'

**Comment by Ju1810** [comment]
I also receive the same error for this book

D:\comix-main>python comix.py 255205
Getting auth token . . .
255205 : My Hero Academia - v01
Downloading page 000 . . .Traceback (most recent call last):
  File "D:\comix-main\comix.py", line 155, in <module>
    cmx.download()
  File "D:\comix-main\comix.py", line 131, in download
    zf.extractall(content_folder, pwd=image_key)
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2106, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2159, in _extract_member
    with self.open(member, pwd=pwd) as source, \
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2013, in open
    return self._open_to_read(mode, zinfo, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2024, in _open_to_read
    raise e
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 2021, in _open_to_read
    return self.zipextfile_cls(zef_file, mode, zinfo, True, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 1203, in __init__
    self.read_init()
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 1218, in read_init
    self._decrypter = self.get_decrypter()
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile.py", line 1306, in get_decrypter
    decrypter = self._decrypter_cls(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyzipper\zipfile_aes.py", line 61, in __init__
    raise RuntimeError("Bad password for file %r" % zinfo.filename)
RuntimeError: Bad password for file 'COMIXOLOGY_BOOK_ENCRYPTED_HD_0001.jpg'

**Comment by Ju1810** [comment]
I've seen the other resolved issue saying it's a publisher Id problem but I don't know how to find the Id
The publisher for the first book is  BOOM! - BOOM! Box 
and the second book is VIZ Media: SHONEN JUMP

**Comment by OverPT** [comment]
The same is happening to me. Is there any more info about this issue?

**Comment by Zaphain** [comment]
> I've seen the other resolved issue saying it's a publisher Id problem but I don't know how to find the Id...

My post here should help you:
https://github.com/athrowaway2021/comix/issues/39#issuecomment-1374313352
