### ISSUE TITLE
Still Getting 2FA error

### ISSUE THREAD

**Issue by MrNiceGuyBR** [athrowaway2021/comix#44]
Still Getting 2FA error. I'm still getting "Could not get auth token" error, even after login/logout in my account and running the program again:

C:\comix-main>python comix.py list
Getting auth token . . .
{"response": {"challenge": {"challenge_reason": "HandleOnWebView", "uri": "https://www.amazon.com/ap/challenge?arb=370d12b1-17b0-4720-b6be-c2f4d779cef3"}}, "request_id": "01cd1df43kilokh521548c0132066"}
Amazon needs to reconfirm your identity with 2FA. Please logout and login again in your browser.
Traceback (most recent call last):
  File "C:\comix-main\comix.py", line 152, in <module>
    cmx = Cmx(None)
          ^^^^^^^^^
  File "C:\comix-main\comix.py", line 27, in __init__
    raise Exception("Could not get auth token")
Exception: Could not get auth token

**Comment by MrNiceGuyBR** [comment]
Solved: I've just deleted the device_ID file from comix-main and then hit the "python comix.py list" again.
