### ISSUE TITLE
TypeError: Couldn't parse file content!

### ISSUE THREAD

**Issue by mooow** [athrowaway2021/comix#5]
Hi!

I tried running your code, and I got the following error:

```root@c6f37767843a:/comix# python comix.py
Traceback (most recent call last):
  File "/comix/comix.py", line 13, in <module>
    import comix_pb2
  File "/comix/comix_pb2.py", line 16, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 965, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't parse file content!
```

I run the code on a docker container:
```
$ docker -ti python bash
# git clone 'https://github.com/athrowaway2021/comix.git'
# cd comix/
# pip install -r requirements.txt
# apt update; apt install vim
# vim config.py # For setting the AUTH_TOKEN
# python comix.py
```

I think the problem has to do with `serialized_pb` being invalid in `comix_pb2.py` at line 22.

Let me know if there is any other information that I can give you or if I am doing something wrong.

-------

### EDIT on 2021-04-20T21:26:27+02:00

I tried to troubleshoot this by running `git bisect` but I found no solution whatsoever. Since the application seem to be working for other people the only thing that comes to mind is that the problem might be related to the dependencies' versions.

These are the versions of the dependencies that I have installed by running `pip install -r requirements.txt` in both a completely new virtualenv in my local machine (`python --version` is `Python 3.8.0`)  and the docker container pulled from python/latest (`python --version` is `Python 3.9.4`). In both cases pip installs the same version for the dependencies.

```
$ pip freeze
certifi==2020.12.5
chardet==4.0.0
idna==2.10
protobuf==3.15.8
pycryptodomex==3.10.1
pyzipper==0.3.5
requests==2.25.1
six==1.15.0
urllib3==1.26.4
```

Let me know if you have older versions installed.

**Comment by mooow** [comment]
I solved by forcing `protobuf` version to `3.14.0` by running `pip install protobuf=3.14.0`.

For the future i suggest to generate your requirements.txt by running `pip freeze > requirements.txt`: that way people will install the exact same version as you had in your local machine (that supposedly works).

I suggest updating the requirements.txt as following:
```
protobuf==3.14.0
pyzipper==0.3.5
requests==2.25.1
```

which are the versions that work for me.
