### ISSUE TITLE
Can not authenticate (2FA)

### ISSUE THREAD

**Issue by OverPT** [athrowaway2021/comix#55]
I don't have the 2FA turned on on my amazon account, but this error message appears when I try to use unkindle.py:

Amazon needs to reconfirm your identity with 2FA. Please logout and login again in your browser.
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\User\Downloads\comix\comix-main\unkindle.py", line 186, in <module>
    kindle = Kindle(args.asin, hdv_png=not args.jpeg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\Downloads\comix\comix-main\unkindle.py", line 26, in __init__
    raise Exception("Could not authenticate!")
Exception: Could not authenticate!

2FA is off, logged out and logged in several times, same error message.

**Comment by athrowaway2021** [comment]
What domain is the account registered on? (amazon.com, .co.uk, .co.jp, etc) Could you try changing the domain in config.py if it is different?

**Comment by OverPT** [comment]
It was "com". Changed to "com" in that file, but same error. Tried with "es" and "co.uk" too.

**Comment by texhy** [comment]
I am having the same issue even though the 2FA is disabled but still. I have also changed the config.py file to .jp which is my desired domain.

**Comment by tootiredtosleep42** [comment]
Having the same error here since august.
Can't login, even tried deactivating 2FA, making a new account with no phone number or TFA, it always gives "Amazon needs to reconfirm your identity with 2FA. Please logout and login again in your browser."

Any news or workarounds to this?

**Comment by atinez1988-hub** [comment]
Having the same issue.
