### ISSUE TITLE
KeyError: 'YJFragmentList get has multiple matches

### ISSUE THREAD

**Issue by vee-eye-en-kay** [athrowaway2021/comix#56]
This has worked mostly well with the books I have attempted, except for this one: **B0BPX4YJ8V**

```
Microsoft Windows [Version 10.0.22631.3085]
(c) Microsoft Corporation. All rights reserved.

D:\comix-main>python unkindle.py B0BPX4YJ8V
Authenticating . . .
Logged in with saved state
Authenticated!
Download size: 124MB
Downloading the book . . . 97%
Extracting . . .
Traceback (most recent call last):
  File "D:\comix-main\unkindle.py", line 188, in <module>
    kindle.download(args.output, args.keep_temp)
  File "D:\comix-main\unkindle.py", line 138, in download
    metadata = self.book.get_metadata()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comix-main\third_party\kfxlib\yj_book.py", line 156, in get_metadata
    if self.has_metadata() and self.has_cover_data():
       ^^^^^^^^^^^^^^^^^^^
  File "D:\comix-main\third_party\kfxlib\yj_metadata.py", line 246, in has_metadata
    self.fragments.get(YJFragmentKey(ftype="$258")) is not None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comix-main\third_party\kfxlib\yj_container.py", line 322, in get
    raise KeyError("YJFragmentList get has multiple matches for %s: %s" % (repr(key), list_symbols(matches)))
KeyError: 'YJFragmentList get has multiple matches for $258::: $258::, $258::'

D:\comix-main>
```

I have tried to delete the output folder it created, then retrying the process from the start, but continue to get the same error each time. It seems to always happen after the "download" gets to 97% and begins to extract, then error. 

Other books before this one and after, have not received any errors on my end. My script knowledge is extremely limited so I don't know how to troubleshoot.

**Comment by 2023comicjtr** [comment]
I received the same error (on a different book), and like you, the error always appeared after the downloading was complete and the extraction process started.  I never found a solution, but I was able to successfully grab the book by using the less elegant method discussed in a different thread (use an Android emulator, import into Calibre, then use the terminal to extract).  Obviously that doesn't solve this problem, but I was able to grab the book I was after!

Edit:  oops... this thread: https://github.com/noDRM/DeDRM_tools/discussions/440

**Comment by ghost** [comment]
I haven't yet encountered this myself. Assuming the above comment is true, I'm not sure why comix would be failing here when KFX Input doesn't. KFX Input's version history mentions addressing similar issues in v1.18.0 and v1.31.0.

In the meantime, if the problem is only with extraction, you should at least be able to avoid setting up an Android emulator. Use the `--keep_temp` arg mentioned in the README. After downloading and presumably failing extraction, you should have an output folder with the KFX files inside (e.g. `comix/output/B0BPX4YJ8V`). These can be imported to calibre after adding the `device_id` from `state.json` to DeDRM_tools.

**Comment by SYY-b** [comment]
For what it's worth, I ran into this issue on a few books now.  Luckily, on failure, even without `--keep_temp`, the tool leaves the downloaded files in the temp folder. I was able to import the KFX into Calibre by adding just one of the KFX files in the temp folder.

For each case of the first issue, I hit a second issue using Calibre to convert the KFX due to [noDRM/DeDRM_tools#1818](https://github.com/apprenticeharper/DeDRM_tools/issues/1818). ~~Maybe related?~~ Edit: I realize now Calibre simply does not support converting fixed-layout KFX books directly, i.e. comics.

To work around the Calibre conversion limitations, I was able to use the KFX Input plugin CLI, as the conversion error message suggests.

These were the affected ASIN I have encountered so far:
- B01GT6BLX8
- B00F3HK6TA
- B071NX66W6

Weirdly, books in the same series worked fine, so it seems kinda random. Hopefully this context is helpful.

**Comment by whatveer** [comment]
> For what it's worth, I ran into this issue on a few books now. Luckily, on failure, even without `--keep_temp`, the tool leaves the downloaded files in the temp folder. I was able to import the KFX into Calibre by adding just one of the KFX files in the temp folder.
> 
> For each case of the first issue, I hit a second issue using Calibre to convert the KFX due to [noDRM/DeDRM_tools#1818](https://github.com/apprenticeharper/DeDRM_tools/issues/1818). ~Maybe related?~ Edit: I realize now Calibre simply does not support converting fixed-layout KFX books directly, i.e. comics.
> 
> To work around the Calibre conversion limitations, I was able to use the KFX Input plugin CLI, as the conversion error message suggests.
> 
> These were the affected ASIN I have encountered so far:
> 
> * B01GT6BLX8
> * B00F3HK6TA
> * B071NX66W6
> 
> Weirdly, books in the same series worked fine, so it seems kinda random. Hopefully this context is helpful.

can you explain how you did this? I am having the same issue now

**Comment by LoganTHarvell** [comment]
> can you explain how you did this? I am having the same issue now

If you have Calibre and the KFX Input plug-in installed on your computer, then you should be able to use the command line to decrypt the book into any supported format of your choosing.

Take a look at the Command Line Interface section [here](https://www.mobileread.com/forums/showthread.php?t=291290).

As a tip, you only need to specify any _one_ single kfx, azw, etc. file from the folder that contains the files, and it will properly detect the related files and decrypt them into a single book.

**Comment by SYY-b** [comment]
> can you explain how you did this? I am having the same issue now

If you have Calibre and the KFX Input plug-in installed on your computer, then you should be able to use the command line to decrypt the book into any supported format of your choosing.

Take a look at the Command Line Interface section [here](https://www.mobileread.com/forums/showthread.php?t=291290).

As a tip, you only need to specify any _one_ single kfx, azw, etc. file from the folder that contains the files, and it will properly detect the related files and decrypt them into a single book.

**Comment by bluetyson** [comment]
Trying this and the error is

```python
Processing G:\comix\output\B00CIID2FW\CR!749KNEZQ2553VFH399AF79HCKHH2.kfx
Processing container: G:\comix\output\B00CIID2FW\CR!749KNEZQ2553VFH399AF79HCKHH2.kfx
ERROR: Book is incomplete. All of the KFX container files that make up the book must be combined into a KFX-ZIP file for successful conversion. (Missing containers CR!9MFA9VNJ9X0JF7XPGDD6TMSK2XKE, CR!B6ZJMFZ61978S8ZF07Z87JF13F55, CR!CSHVR7ZSD151Q3P51QDZS9C2964F, CR!F20KWWYE1N7A9ETMWKR9S14QY3GR, CR!G89WT8FCBD1D17F7718PFQHSNCQM, CR!H56BW8EB551KF0R10A66FFG7P3Y8, CR!HKH64DT71S093ETQA3J2FYWK1PRR, CR!P60M1JBW3D3YH1YDWW9QCCJ8TD99, CR!W3RTC6PMVN0K5083B24TREKGZ5VC, CR!ZHFXDYKF9X019AX8C2826QVN8BN3)
ERROR: Book is incomplete. All of the KFX container files that make up the book must be combined into a KFX-ZIP file for successful conversion. (Missing fragments $264, $265, $538, $550)
WARNING: Reading order has extra sections: c0, c10, c10U, c13A, c14J, c17P, c1A6, c1CP, c1F6, c1HP, c46, c5E, c7M, c8, c8W, cB2, cCY, cFE, cH0, cK3, cMB, cP, cPV, cSR, cUX, cW5, cYB
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 95, in <module>
  File "site.py", line 90, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\debug.py", line 283, in main
  File "calibre_plugins.kfx_input.__init__", line 190, in cli_main
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 224, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_structure", line 693, in check_consistency
  File "calibre_plugins.kfx_input.kfxlib.yj_position_location", line 105, in check_position_and_location_maps
  File "calibre_plugins.kfx_input.kfxlib.yj_position_location", line 564, in collect_content_position_info
  File "calibre_plugins.kfx_input.kfxlib.yj_position_location", line 542, in collect_section_position_info
  File "calibre_plugins.kfx_input.kfxlib.yj_container", line 327, in __getitem__
KeyError: 'YJFragmentList item is missing: c0:: $260::'
```

Does this suggest just a download failure?

**Comment by bluetyson** [comment]
Same original error if I check that by trying again though:

```python
Downloading the book . . . 92%
Extracting . . .
Traceback (most recent call last):
  File "G:\comix\unkindle.py", line 188, in <module>
    kindle.download(args.output, args.keep_temp)
  File "G:\comix\unkindle.py", line 138, in download
    metadata = self.book.get_metadata()
  File "G:\comix\third_party\kfxlib\yj_book.py", line 156, in get_metadata
    if self.has_metadata() and self.has_cover_data():
  File "G:\comix\third_party\kfxlib\yj_metadata.py", line 246, in has_metadata
    self.fragments.get(YJFragmentKey(ftype="$258")) is not None)
  File "G:\comix\third_party\kfxlib\yj_container.py", line 322, in get
    raise KeyError("YJFragmentList get has multiple matches for %s: %s" % (repr(key), list_symbols(matches)))
KeyError: 'YJFragmentList get has multiple matches for $258::: $258::, $258::'
```
